### ISSUE TITLE
Commentators/Interview layout

### ISSUE THREAD

**Issue by locks** [AlexRodwell/netrunner-stream-overlay#12] opened 2023-10-19 13:11 UTC
We could do this in OBS, but seems much easier to update in the overlay.

Have an overlay with the names of the commentators that we can show e.g. at the beginning of the game for a little bit.

Relatedly, have a layout for interviews with name tags for the different peeps.

**Comment by AlexRodwell** [comment] 2024-06-13 22:50
Closing, duplicate of https://github.com/AlexRodwell/netrunner-stream-overlay/issues/14

**Closed by AlexRodwell** 2024-06-13 22:50 UTC
